[package]
name = "aardwolf-types"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
edition = "2018"

[features]
default = []
use-rocket = ["rocket", "rocket_codegen", "aardwolf-models/rocket"]
use-actix = ["actix-web", "actix", "futures"]

[dependencies]
actix = { version = "0.7", optional = true }
actix-web = { version = "0.7", optional = true }
derive_builder = "0.5.0"
failure = "0.1"
futures = { version = "0.1", optional = true }
rocket = { version = "0.3.17", optional = true }
rocket_codegen = { version = "0.3.17", optional = true }
r2d2 = "0.8"
r2d2-diesel = "1.0"
serde = "1.0"
serde_derive = "1.0"
url = "1.7"
url_serde = "0.2"

[dependencies.aardwolf-models]
version = "0.1"
path = "../aardwolf-models"

[dependencies.diesel]
version = "1.1"
default-features = false
features = ["postgres", "uuid", "chrono"]
