version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: aardwolf
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: aardwolf
      PGDATA: /var/lib/postgres/data
    ports: 
      - 5432:5432
    networks: 
      - 'default'

  app:
    build: .
    ports: 
      - 8080:8080
    depends_on: 
      - db
    networks: 
      - 'default'
    links: 
      - db
    command: ["./wait-for-it.sh", "db:5432", "./setup"]
  


networks:
  default:
    driver: 'bridge'
