FROM rust:1.71-slim-bullseye

RUN apt-get --yes update && apt-get --yes install git pkg-config libssl-dev
RUN cargo install wasm-bindgen-cli
RUN cargo install trunk
RUN rustup target add wasm32-unknown-unknown
RUN rustup component add clippy-preview
RUN rustup component add rustfmt