pub mod aardwolf {
    table! {
        /// Representation of the `aardwolf.accounts` table.
        ///
        /// (Automatically generated by Diesel.)
        aardwolf.accounts (id) {
            /// The `id` column of the `aardwolf.accounts` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `username` column of the `aardwolf.accounts` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            username -> Varchar,
            /// The `domain` column of the `aardwolf.accounts` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            domain -> Nullable<Varchar>,
            /// The `display_name` column of the `aardwolf.accounts` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            display_name -> Varchar,
            /// The `created_at` column of the `aardwolf.accounts` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `aardwolf.accounts` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }
    
    table! {
        /// Representation of the `aardwolf.users` table.
        ///
        /// (Automatically generated by Diesel.)
        aardwolf.users (id) {
            /// The `id` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `email` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            email -> Varchar,
            /// The `encrypted_password` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            encrypted_password -> Varchar,
            /// The `account_id` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            account_id -> Uuid,
            /// The `admin` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            admin -> Bool,
            /// The `disabled` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            disabled -> Bool,
            /// The `unconfirmed_email` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            unconfirmed_email -> Varchar,
            /// The `confirmation_token` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Bytea`.
            ///
            /// (Automatically generated by Diesel.)
            confirmation_token -> Bytea,
            /// The `confirmed_at` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Nullable<Timestamp>`.
            ///
            /// (Automatically generated by Diesel.)
            confirmed_at -> Nullable<Timestamp>,
            /// The `confirmation_sent_at` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Nullable<Timestamp>`.
            ///
            /// (Automatically generated by Diesel.)
            confirmation_sent_at -> Nullable<Timestamp>,
            /// The `created_at` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `aardwolf.users` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }
    
    joinable!(users -> accounts (account_id));
}
