[package]
name = "aardwolf-rocket"
version = "0.1.0"
authors = ["Eric Chadbourne <sillystring@protonmail.com>", "Elijah Mark Anderson <kd0bpv@gmail.com>", "Paul Woolcock <paul@woolcock.us>", "asonix <asonix@asonix.dog>"]
description = "Powering connected social communities with free software."

[features]
default = []

[dependencies]
bs58 = "0.2"
bcrypt = "0.2"
collection_macros = "0.2.0"
config = "0.8.0"
derive_builder = "0.5.0"
failure = "0.1.1"
r2d2 = "0.8"
r2d2-diesel = "1.0"
ring = "0.11"
rocket = "0.3.17"
rocket_codegen = "0.3.17"
serde = "1.0.21"
serde_derive = "1.0.21"
url = "1.7"
url_serde = "0.2"
yaml-rust = "0.3.5"
log = "0.4.1"
# Use syslog for writing logs. Conflicts with use-systemd and log-* features.
syslog = { version = "4.0.0", optional = true }
# Integrate with Systemd, includes Journald for logging. Conflicts with log-*
# features.
systemd = { version = "0.3.0", optional = true }
# Use simple log files or stdout/stderr. Conflicts with use-systemd and
# log-* features.
simple-logging = {version = "2.0.1", optional = true}

[dependencies.aardwolf-models]
version = "0.1"
path = "../aardwolf-models"
features = ["rocket"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.diesel]
version = "1.1"
default-features = false
features = ["postgres", "uuid", "chrono"]

[dependencies.rocket_contrib]
version = "0.3.17"
default-features = false
features = ["handlebars_templates", "json"]

[dependencies.uuid]
version = "0.6"
features = ["v4"]
