name = "aardwolf-server"
version = "unknown"
author = "Please see README for credits"
about = "Powering connected social communities with open software."

[[args]] # Define table array "args"
[args.config] # Sub-table of "args"
short = "c"
long = "config"
value_name = "CFG_FILE"
help = "Sets a custom config file"
takes_value = true

[args.log] # Also a sub-table of "args"
short = "l"
long = "log"
value_name = "LOG_FILE"
help = "Sets logging destination"
takes_value = true

[args.verbose] # Also a sub-table of "args"
short = "v"
multiple = true
help = "Sets the level of verbosity"