[multipurpose]
instanceTitle = "Aardwolf Instance"
return = "Go back"
submit = "Submit"
commentPlaceholder = "Add a comment..."

[asideSettings]
settings = "Settings"
editProfile = "Edit Profile"
preferences = "Preferences"
muteWords = "Muted Keywords"
muteUsers = "Muted Users"
notifications = "Notifications"
security = "Security"
dataImport = "Data Import"
dataExport = "Data Export"
authApps = "Authorized Apps"
authFollow = "Authorized Followers"
invites = "Invite People"

[asideShortcuts]
news = "News Feed"
messages ="Messages"
shortcuts = "Shortcuts"
calendar = "Calendar"
groups = "Groups"
lists = "Lists"
photos = "Photos"
favorites = "Favorites"
weather = "Weather"
create = "Create"
newEvent = "New Event"
newGroup = "New Group"

[profileEdit]
profileTitle = "Edit Profile"
profileSubTitle = "Subtitle"
profileDisplayName = "Display Name"
profileCharRemaining = "characters left"
profileBio = "About you"
profileAvatarUpload = "Upload Avatar"
profileAvatarUploadBtnLabel = "Choose a file…"
profileAvatarFileName = "No file chosen"
profileAvatarSubText = "PNG, GIF or JPG. At most 2MB. Will be downscaled to 120x120px"
profileHeaderUpload = "Upload Avatar"
profileAvatarHeaderLabel = "Choose a file…"
profileHeaderFileName = "No file chosen"
profileHeaderSubText = "PNG, GIF or JPG. At most 2MB. Will be downscaled to 700x335px"

[messaging]
enterPost = "Press enter to awoo"
post = "Awoo"
reply = "Rewoo"

[footer]
terms = "Terms of Service"
copyright = "Copyright 2018"
github = "Check us out on GitHub"
donate = "Buy the team a coffee"
