[multipurpose]
instanceTitle = "Instancja Aardwolfa"
return = "Wróć"
submit = "Wyślij"
commentPlaceholder = "Dodaj komentarz…"

[asideSettings]
settings = "Ustawienia"
editProfile = "Edytuj profil"
preferences = "Preferencje"
muteWords = "Wyciszone słowa"
muteUsers = "Wyciszeni użytkownicy"
notifications = "Powiadomienia"
security = "Bezpieczeństwo"
dataImport = "Importowanie danych"
dataExport = "Eksportowanie danych"
authApps = "Uwierzytelnione aplikacje"
authFollow = "Zatwierdzeni śledzeni"
invites = "Zaproś ludzi"

[asideShortcuts]
news = "Aktualności"
messages ="Wiadomości"
shortcuts = "Skróty"
calendar = "Kalendarz"
groups = "Groupy"
lists = "Listy"
photos = "Zdjęcia"
favorites = "Ulubione"
weather = "Pogoda"
create = "Utwórz"
newEvent = "Nowe wydarzenie"
newGroup = "Nowa grupa"

[profileEdit]
profileTitle = "Edytuj profil"
profileSubTitle = "Podpis"
profileDisplayName = "Nazwa wyświetlana"
profileCharRemaining = "pozostałych znaków"
profileBio = "O Tobie"
profileAvatarUpload = "Wyślij awatar"
profileAvatarUploadBtnLabel = "Wybierz plik…"
profileAvatarFileName = "Nie wybrano pliku"
profileAvatarSubText = "PNG, GIF lub JPG. Co najwyżej 2MB. Zostanie pomniejszony do 120x120px"
profileHeaderUpload = "Wyślij awatar"
profileAvatarHeaderLabel = "Wybierz plik…"
profileHeaderFileName = "Nie wybrano pliku"
profileHeaderSubText = "PNG, GIF lub JPG. Co najwyżej 2MB. Zostanie pomniejszony do 700x335px"

[messaging]
enterPost = "Naciśnij, aby zawyć"
post = "Awoo"
reply = "Rewoo"

[footer]
terms = "Zasady użytkowania"
copyright = "Prawa autorskie 2018"
github = "Odwiedź projekt na GitHubie"
donate = "Kup kawę zespołowi"
