[multipurpose]
instance_title = "Aardwolf Instance"
return = "Go back"
submit = "Submit"
comment_placeholder = "Add a comment..."

[aside_settings]
settings = "Settings"
edit_profile = "Edit Profile"
preferences = "Preferences"
mute_words = "Muted Keywords"
mute_users = "Muted Users"
notifications = "Notifications"
security = "Security"
data_import = "Data Import"
data_export = "Data Export"
auth_apps = "Authorized Apps"
auth_follow = "Authorized Followers"
invites = "Invite People"

[aside_shortcuts]
news = "News Feed"
messages ="Messages"
shortcuts = "Shortcuts"
calendar = "Calendar"
groups = "Groups"
lists = "Lists"
photos = "Photos"
favorites = "Favorites"
weather = "Weather"
create = "Create"
new_event = "New Event"
new_group = "New Group"

[profile_edit]
profile_title = "Edit Profile"
profile_sub_title = "Subtitle"
profile_display_name = "Display Name"
profile_char_remaining = "characters left"
profile_bio = "About you"
profile_avatar_upload = "Upload Avatar"
profile_avatar_upload_btn_label = "Choose a file…"
profile_avatar_file_name = "No file chosen"
profile_avatar_sub_text = "PNG, GIF or JPG. At most 2MB. Will be downscaled to 120x120px"
profile_header_upload = "Upload Avatar"
profile_avatar_header_label = "Choose a file…"
profile_header_file_name = "No file chosen"
profile_header_sub_text = "PNG, GIF or JPG. At most 2MB. Will be downscaled to 700x335px"

[messaging]
enter_post = "Press enter to post"
post = "Post"
reply = "Reply"

[footer]
terms = "Terms of Service"
copyright = "Copyright 2018"
github = "Check us out on GitHub"
donate = "Buy the team a coffee"
