[package]
name = "aardwolf-models"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
description = "Database interaction for the Aardwolf project"

[dependencies]
bcrypt = "0.2"
chrono = "0.4"
chrono-tz = "0.5"
failure = "0.1"
log = "0.4"
mime = "0.3"
rand = "0.5"
rocket = { version = "0.3.14", optional = true }
serde = "1.0"
serde_json = "1.0"
url = "1.7"

[features]
default = []

[dependencies.diesel]
version = "1.2"
features = ["chrono", "postgres", "serde_json"]

[dev-dependencies]
dotenv = "0.13"
env_logger = "0.5"
