[package]
name = "aardwolf-models"
version = "0.1.0"
authors = ["asonix <asonix.dev@gmail.com>"]
description = "Database interaction for the Aardwolf project"

[dependencies]
bcrypt = "0.2"
chrono = "0.4"
chrono-tz = "0.4"
failure = "0.1"
log = "0.4"
mime = "0.3"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"

[dependencies.diesel]
version = "1.2"
features = ["chrono", "postgres", "serde_json"]

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
rev = "55459db7732b9a240826a5c120c650f87e3372ce"

[dependencies.pear]
git = "https://github.com/SergioBenitez/Pear"
rev = "b4751403ed9a06bc813b662334f0a555eccae6a0"

[dependencies.pear_codegen]
git = "https://github.com/SergioBenitez/Pear"
rev = "b4751403ed9a06bc813b662334f0a555eccae6a0"

[dev-dependencies]
dotenv = "0.13"
env_logger = "0.5"
