name: Aardwolf-Social/test
on:
  workflow_run:
    workflows:
      - Aardwolf-Social/build
    types:
      - completed

jobs:
 
  Aardwolf-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/aardwolf-build.yml
  
    - name: Cargo test aardwolf  
      run: cargo test --all --verbose