---
name: Test

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  cargo-test:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
      - name: Cargo test Aardwolf  
        run: cargo test --all --verbose