---
name: Test

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  cargo-test:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
      # Checkout the originating  branch 
      - uses: actions/checkout@v4 
        with:
          ref: ${{ github.event.workflow_run.head_branch }}     
  
      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
  
      # Run cargo test
      - name: Cargo test Aardwolf  
        run: cargo test --all --verbose