name: Aardwolf-Social/test
on:
  workflow_run:
    workflows: ["Aardwolf-Social/build"]
    branches: 
      - "**/*"
    types: 
      - completed

jobs:
 
  Test-Aardwolf-Build:
    runs-on: ubuntu-latest

    steps:

      - name: Cargo test aardwolf  
        run: cargo test --all --verbose