#-
# CLI + GitHub action to combine dependabot PRs on GitHub repositories.
# https://github.com/marketplace/actions/batch-dependabot-prs

name: "Combine Dependabot PRs"
on:
  workflow_call:
    inputs:
      branches:
        description: 'Comma separate string of PRs to combine'
        required: false
        type: string

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        # Gita To Do: test here if works
        with:
          persist-credentials: false
      - uses: gita-codaio/batch-dependabot@main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          ignoreLabel: "nocombine"
          baseBranch: "main"
          openPR: true
          allowSkipped: false
