#-
# GitHub Action for Rust Builds
# Default script added 2023-06-02
#

name: Rust Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Package installation 
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev
    - run: sudo apt-get remove -y libssl-dev
    - uses: actions/cache@v3
        with:
          path: /opt/openssl
        
    # Cargo build    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
