#-
# GitHub Action for Building Aardwolf
#
name: 'Travis.yml conversion'

on:
  push:
    branches:
      - master
      - 'banjofox/*'
  pull_request:
    branches:
      - master
jobs:

#-
# Build Rust
# Source: https://github.com/marketplace/actions/setup-rust
#
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - name: Build | Lint
        run: cargo clippy
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo check
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build | Compile
        run: cargo test
#-
# Continue to build Aardwolf
#        
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    # Postgres Service      
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
     
      # Postgres prep
      - run: psql --version
      - run: |
          psql -c 'create user pguser;' -U postgres
          psql -c 'alter user pguser createdb; ' -U postgres
        env:
          PGHOST: 127.0.0.1
      
      # Do stuff...    
      - uses: actions/checkout@v2
      - run: echo "BEFORE SCRIPT"
      - run: psql -c 'CREATE DATABASE aardwolf_testing;' -U postgres
      - run: >-
          if which diesel; then echo "diesel already installed"; else cargo
          install diesel_cli --no-default-features --features=postgres; fi
      - run: >-
          echo 'DATABASE_URL=postgres://postgres@localhost/aardwolf_testing' >
          .env
      - run: >-
          echo
          'TEST_DATABASE_URL=postgres://postgres@localhost/aardwolf_testing' >>
          .env
      - run: pushd aardwolf-models
      - run: diesel migration run
      - run: popd
      - run: echo "SCRIPT"
      - run: cargo build --all --verbose
      - run: cargo test --all --verbose

      # Cargo build    
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose      
